apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-controller
  namespace: argocd
spec:
  destination:
    namespace: myargocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-dev
    repoURL: https://github.com/kamalpunn/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
